# Generated by Django 3.1.7 on 2021-05-12 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLoginRecord',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.CharField(max_length=50)),
                ('userID', models.IntegerField()),
                ('username', models.CharField(max_length=50)),
                ('detail', models.CharField(max_length=50)),
            ],
        ),
    ]
